import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
  ArrowRight,
  Check,
  CheckCircle2,
  Download,
  ExternalLink,
  RotateCcw,
  Workflow,
} from 'lucide-react';
import { repositoryService } from '../services/repositoryService';
import type { CompletionReportData } from '../types';

export const OnboardingCompletionPage: React.FC = () => {
  const navigate = useNavigate();
  const [report, setReport] = useState<CompletionReportData | null>(null);
  const [copiedNotification, setCopiedNotification] = useState<string | null>(null);

  useEffect(() => {
    repositoryService.getCompletionReport().then(data => {
      setReport(data);
    });
  }, []);

  if (!report) {
    return (
      <main className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex items-center justify-center">
        <div className="flex items-center gap-2 text-sm text-muted-foreground font-mono">
          <span className="w-2 h-2 rounded-full bg-primary animate-pulse"></span>
          <span>Loading completion report...</span>
        </div>
      </main>
    );
  }

  const { repository, summaryMetrics, pipeline, domains, history } = report;

  const handleExport = () => {
    const reportText = `# RepoGuide Onboarding Verification Report
Repository: ${repository.name} (${repository.url})
Branch: ${repository.branch}
Status: 100% Complete (${report.verifiedTasks}/${report.totalTasks} Tasks Verified)
Total Time: ${report.totalDuration}

## Verified Competencies
${domains.map(d => `- [x] ${d.number} ${d.title}: ${d.description} (${d.status})`).join('\n')}

## Architecture Pipeline
${pipeline.join(' -> ')}

## Task History
${history.map(h => `- Task ${h.number} (${h.title}): Verified in ${h.duration}`).join('\n')}

---
Generated by RepoGuide Developer Onboarding Platform`;

    const blob = new Blob([reportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${repository.name.toLowerCase()}-onboarding-report.md`;
    link.click();
    URL.revokeObjectURL(url);

    setCopiedNotification('Report exported to Markdown.');
    setTimeout(() => setCopiedNotification(null), 3000);
  };

  return (
    <div className="flex-1 flex flex-col w-full">
      {/* 1. Breadcrumb Sub-bar */}
      <div className="w-full border-b border-border bg-secondary/30 px-4 sm:px-6 lg:px-8 py-2.5 transition-colors duration-150">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <nav className="flex items-center gap-2 text-xs font-mono text-muted-foreground flex-wrap">
            <Link to="/" className="hover:text-foreground transition-colors duration-150">
              Repositories
            </Link>
            <span>/</span>
            <Link
              to="/overview"
              className="text-foreground hover:text-primary font-medium transition-colors duration-150"
            >
              {repository.name}
            </Link>
            <span>/</span>
            <Link
              to="/onboarding"
              className="hover:text-foreground transition-colors duration-150"
            >
              Onboarding
            </Link>
            <span>/</span>
            <span className="text-primary font-medium">Complete</span>
          </nav>

          <div className="flex items-center gap-2 self-start sm:self-auto font-mono text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-card border border-border">
              <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
              branch: {repository.branch}
            </span>
            <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-card border border-border">
              commit: a4c89f2
            </span>
          </div>
        </div>
      </div>

      {/* Main Content Canvas */}
      <main className="flex-1 w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-12">
        {/* 2. Completion Header */}
        <section className="text-center max-w-2xl mx-auto space-y-3">
          {/* Status Pill */}
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-border bg-secondary font-mono text-xs text-primary tracking-wide">
            <span className="inline-block w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
            <span>ONBOARDING COMPLETE</span>
          </div>

          <h1 className="text-2xl sm:text-3xl lg:text-4xl font-semibold text-foreground tracking-tight">
            You're ready to explore the codebase.
          </h1>
          <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
            You completed the RepoGuide onboarding journey and verified your understanding of the
            project's core architecture and workflows.
          </p>
        </section>

        {/* 3. Completion Metric Card (Non-gamified, Structural Precision) */}
        <section className="max-w-2xl mx-auto">
          <div className="border border-border rounded-xl bg-card p-6 space-y-4 shadow-xs">
            <div className="flex items-baseline justify-between">
              <div>
                <div className="text-3xl sm:text-4xl font-semibold text-foreground leading-none tracking-tight">
                  {report.verifiedTasks} / {report.totalTasks}
                </div>
                <div className="text-xs sm:text-sm text-muted-foreground mt-1">Tasks verified</div>
              </div>
              <div className="text-right">
                <span className="text-xs font-mono text-primary px-2.5 py-1 rounded border border-border bg-secondary font-medium">
                  100% COMPLETE
                </span>
              </div>
            </div>

            {/* 100% Progress Bar */}
            <div className="w-full bg-secondary h-1.5 rounded-full overflow-hidden">
              <div className="bg-primary h-full w-full rounded-full transition-all duration-500 ease-out"></div>
            </div>

            {/* Verification status label */}
            <div className="flex items-center gap-2 pt-1 text-xs font-mono text-muted-foreground">
              <CheckCircle2 className="w-3.5 h-3.5 text-primary shrink-0" />
              <span>
                All {report.totalTasks} onboarding tasks verified and completed · 100% verified
              </span>
            </div>
          </div>
        </section>

        {/* 4. What You Verified (6 Verified Competencies Grid) */}
        <section className="space-y-4">
          <div className="border-b border-border pb-3 flex items-end justify-between">
            <div>
              <h2 className="text-base sm:text-lg font-semibold text-foreground tracking-tight">
                What you verified
              </h2>
              <p className="text-xs sm:text-sm text-muted-foreground mt-0.5">
                Core competencies and architectural domains tested across the repository
              </p>
            </div>
            <span className="text-xs font-mono text-muted-foreground hidden sm:inline">
              {domains.length} of {domains.length} domains validated
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {domains.map(domain => (
              <div
                key={domain.id}
                className="border border-border rounded-xl bg-card p-4 hover:border-muted-foreground/30 transition-colors flex flex-col justify-between shadow-xs"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm sm:text-base text-foreground font-medium flex items-center gap-1.5">
                      <Check className="w-4 h-4 text-primary stroke-3" />
                      {domain.title}
                    </span>
                    <span className="text-xs font-mono text-muted-foreground px-1.5 py-0.5 rounded border border-border bg-secondary">
                      {domain.number}
                    </span>
                  </div>
                  <p className="text-xs sm:text-sm text-muted-foreground leading-snug">
                    {domain.description}
                  </p>
                </div>

                <div className="mt-4 pt-3 border-t border-border flex items-center justify-between text-xs font-mono text-muted-foreground">
                  <span>{domain.tags}</span>
                  <span className="text-primary font-normal">{domain.status}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* 5. Repository Architecture Summary Card */}
        <section className="space-y-4">
          <div className="border-b border-border pb-3">
            <h2 className="text-base sm:text-lg font-semibold text-foreground tracking-tight">
              Repository Summary
            </h2>
          </div>

          <div className="border border-border rounded-xl bg-card p-6 space-y-5 shadow-xs">
            {/* Header row */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="h-9 w-9 rounded-lg border border-border bg-secondary flex items-center justify-center">
                  <Workflow className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-base font-semibold text-foreground">
                      {repository.name}
                    </span>
                    <a
                      href={repository.url}
                      target="_blank"
                      rel="noreferrer"
                      className="text-muted-foreground hover:text-foreground transition-colors"
                      title="Open repository source"
                    >
                      <ExternalLink className="w-3.5 h-3.5" />
                    </a>
                  </div>
                  <p className="text-xs sm:text-sm text-muted-foreground">
                    Unified student campus engagement &amp; event scheduling infrastructure
                  </p>
                </div>
              </div>

              {/* Tech stack tags */}
              <div className="flex flex-wrap items-center gap-1.5 text-xs font-mono">
                {repository.stack.map(tech => (
                  <span
                    key={tech}
                    className="px-2 py-0.5 rounded border border-border bg-secondary text-foreground"
                  >
                    {tech}
                  </span>
                ))}
              </div>
            </div>

            {/* Architectural Pipeline Strip */}
            <div className="rounded-lg border border-border bg-secondary/30 p-3 font-mono text-xs sm:text-sm text-muted-foreground flex flex-wrap items-center gap-2">
              <span className="text-primary font-medium">Pipeline:</span>
              {pipeline.map((stage, idx) => (
                <React.Fragment key={idx}>
                  <span className="text-foreground">{stage}</span>
                  {idx < pipeline.length - 1 && (
                    <span className="text-muted-foreground/60">→</span>
                  )}
                </React.Fragment>
              ))}
            </div>

            {/* Bottom Metrics & CTA Strip */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2 border-t border-border">
              <div className="flex flex-wrap items-center gap-3 text-xs font-mono text-muted-foreground">
                <span>{summaryMetrics.modules} modules</span>
                <span className="text-muted-foreground/40">·</span>
                <span>{summaryMetrics.routes} API routes</span>
                <span className="text-muted-foreground/40">·</span>
                <span>{summaryMetrics.models} database models</span>
                <span className="text-muted-foreground/40">·</span>
                <span>{summaryMetrics.dependencies} dependencies</span>
              </div>
              <Link
                to="/architecture"
                className="inline-flex items-center gap-1.5 text-xs sm:text-sm text-primary hover:underline font-medium"
              >
                <span>Explore Full Architecture</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        </section>

        {/* 6. Your Onboarding Journey Timeline (Verified Path) */}
        <section className="space-y-4">
          <div className="border-b border-border pb-3 flex items-center justify-between">
            <div>
              <h2 className="text-base sm:text-lg font-semibold text-foreground tracking-tight">
                Your onboarding journey
              </h2>
              <p className="text-xs sm:text-sm text-muted-foreground mt-0.5">
                Sequential verification history and audit timestamps
              </p>
            </div>
            <span className="text-xs font-mono text-muted-foreground">
              Total time: {report.totalDuration}
            </span>
          </div>

          <div className="border border-border rounded-xl bg-card p-6 shadow-xs">
            <div className="relative pl-6 space-y-6 before:absolute before:left-2 before:top-2 before:bottom-2 before:w-px before:bg-border">
              {history.map((item, idx) => (
                <div
                  key={idx}
                  className="relative flex flex-col sm:flex-row sm:items-center justify-between gap-2"
                >
                  <div className="absolute -left-6 top-1 w-4 h-4 rounded-full bg-card border border-primary flex items-center justify-center">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-mono text-muted-foreground">{item.number}</span>
                      <span className="text-sm sm:text-base text-foreground font-medium">
                        {item.title}
                      </span>
                    </div>
                    <p className="text-xs sm:text-sm text-muted-foreground">{item.description}</p>
                  </div>
                  <div className="flex items-center gap-3 text-xs font-mono text-muted-foreground">
                    <span className="text-primary font-normal">Verified ✓</span>
                    <span className="text-muted-foreground/40">·</span>
                    <span>{item.duration}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 7. Developer Readiness & What's Next Callout */}
        <section className="border border-border rounded-xl bg-secondary/30 p-6 sm:p-8 space-y-6 shadow-xs">
          <div className="max-w-2xl space-y-2">
            <h2 className="text-xl sm:text-2xl font-semibold text-foreground tracking-tight">
              What's next?
            </h2>
            <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
              Explore individual modules, inspect the live architecture graph, or return to the
              repository whenever you need more context while writing code.
            </p>
          </div>

          {/* Action buttons */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2 border-t border-border">
            <div className="flex flex-wrap items-center gap-3">
              <Link
                to="/overview"
                className="inline-flex items-center justify-center gap-2 h-9 px-4 rounded-md bg-primary text-primary-foreground text-xs sm:text-sm font-semibold hover:opacity-90 transition-opacity shadow-xs"
              >
                <span>Continue Exploring Repository</span>
                <ArrowRight className="w-4 h-4" />
              </Link>
              <button
                type="button"
                onClick={() => navigate('/onboarding')}
                className="inline-flex items-center justify-center gap-2 h-9 px-4 rounded-md border border-border bg-card text-foreground hover:bg-secondary transition-colors text-xs sm:text-sm font-medium cursor-pointer"
              >
                <RotateCcw className="w-4 h-4" />
                <span>Restart Onboarding</span>
              </button>
            </div>

            {/* Auxiliary action */}
            <div className="flex items-center gap-2 text-xs font-mono text-muted-foreground">
              <button
                type="button"
                onClick={handleExport}
                className="hover:text-foreground transition-colors flex items-center gap-1.5 cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export Verification Report (.md)</span>
              </button>
            </div>
          </div>

          {copiedNotification && (
            <div className="text-xs font-mono text-primary flex items-center gap-1.5 pt-1">
              <Check className="w-3.5 h-3.5" />
              <span>{copiedNotification}</span>
            </div>
          )}
        </section>
      </main>
    </div>
  );
};
